spring:
  application:
    name: service-registry
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

---
server:
  port: 8761
spring:
  config.activate.on-profile: default

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
---
server:
  port: 8762
spring:
  config.activate.on-profile: instance2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
